
# mostly useful for test automation
# if the condition is wrong throughing exception

cartItem = 0

if cartItem != 2:
    #raise Exception("product not matching")

    pass  # whatever the condirion it allows to go to the next logic

assert (cartItem == 0)  # if condition not matching it gives AssertionError


#try - catch method, in python it is try - except method
# it is used where for one certain error we can not stop a testing that time error is handled by try - except method

try:
    with open('rest.txt') as reader:    # if there is no file exist with this name it goes to the except section
        reader.read()

except:
    print('error occured')

# if we want to handle error generated by python we have to use method exception in except part
try:
    with open('rest.txt') as reader:    # if there is no file exist with this name it goes to the except section
        reader.read()

except Exception as pythonError:
    print(pythonError)

finally:
    print("testing complete")

# finally is used with try - except  block. no matter in any failure in try - except block whatever block of data would
# be executed without any failure that block should be written in finally

